package com.example.andichess.chess;

public enum objType {
    FIELD_BLACK, FIELD_WHITE, FIELD_SELECTED,
    ROOK_BLACK, ROOK_WHITE,
    KING_BLACK, KING_WHITE,
    QUEEN_BLACK, QUEEN_WHITE,
    PAWN_BLACK, PAWN_WHITE,
    BISHOP_BLACK, BISHOP_WHITE,
    KNIGHT_BLACK, KNIGHT_WHITE
}